"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase";

type Section="account"|"notifications"|"appearance"|"chat"|"profile"|"blocked";
const sections:{id:Section;label:string}[]=[{id:"account",label:"Account"},{id:"notifications",label:"Notifications"},{id:"appearance",label:"Appearance"},{id:"chat",label:"Chat Settings"},{id:"profile",label:"Profile Settings"},{id:"blocked",label:"Blocked Accounts"}];
export default function CookieSettingsPanel(){
 const supabase=useMemo(()=>createClient(),[]); const [open,setOpen]=useState(false); const [section,setSection]=useState<Section|null>(null); const [uid,setUid]=useState(""); const [email,setEmail]=useState(""); const [profile,setProfile]=useState<any>({}); const [settings,setSettings]=useState<any>({theme:"system",accent_colour:"#a85f1d",default_disappearing:"24_hours",media_auto_download:true,enter_to_send:true,notification_sounds:true,typing_indicators:true,activity_status:true}); const [notifications,setNotifications]=useState<any>({enabled:true,messages:true,story_replies:true,friend_requests:true,friend_acceptances:true,crumb_likes:true,crumb_comments:true,crumb_reposts:true,new_followers:true}); const [blocked,setBlocked]=useState<any[]>([]); const [notice,setNotice]=useState("");
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent).detail;if(d?.view==="settings"){setOpen(true);setSection(null);void load();}};window.addEventListener("cookie:open-settings",h);return()=>window.removeEventListener("cookie:open-settings",h)},[]);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;setUid(user.id);setEmail(user.email||"");const [{data:p},{data:s},{data:n},{data:b}]=await Promise.all([supabase.from("profiles").select("*").eq("id",user.id).maybeSingle(),supabase.from("user_settings").select("*").eq("user_id",user.id).maybeSingle(),supabase.from("notification_settings").select("*").eq("user_id",user.id).maybeSingle(),supabase.from("user_blocks").select("blocked_id,created_at").eq("blocker_id",user.id)]);if(p)setProfile(p);if(s)setSettings(s);else await supabase.from("user_settings").upsert({user_id:user.id});if(n)setNotifications((x:any)=>({...x,...n}));const ids=(b||[]).map((x:any)=>x.blocked_id);if(ids.length){const {data:ps}=await supabase.from("profiles").select("id,display_name,username,avatar_url,profile_colour").in("id",ids);setBlocked(ps||[])}else setBlocked([])}
 async function saveSettings(patch:any){setSettings((x:any)=>({...x,...patch}));const {error}=await supabase.from("user_settings").upsert({user_id:uid,...settings,...patch,updated_at:new Date().toISOString()});if(error)setNotice(error.message)}
 async function saveNotif(key:string,value:boolean){const patch={[key]:value};setNotifications((x:any)=>({...x,...patch}));const {error}=await supabase.from("notification_settings").upsert({user_id:uid,...notifications,...patch,updated_at:new Date().toISOString()});if(error)setNotice(error.message)}
 async function saveProfile(){const {error}=await supabase.from("profiles").update({display_name:profile.display_name,bio:profile.bio,flavour:profile.flavour,profile_colour:profile.profile_colour,interests:profile.interests,updated_at:new Date().toISOString()}).eq("id",uid);setNotice(error?error.message:"Profile saved.")}
 async function changePassword(){const password=window.prompt("Enter your new Cookie password (at least 8 characters):");if(!password)return;if(password.length<8){setNotice("Password must be at least 8 characters.");return}const {error}=await supabase.auth.updateUser({password});setNotice(error?error.message:"Password updated.")}
 async function changeUsername(){const username=window.prompt("New username:",profile.username)?.trim().replace(/^@/,"");if(!username)return;const {error}=await supabase.from("profiles").update({username}).eq("id",uid);if(!error)setProfile((p:any)=>({...p,username}));setNotice(error?error.message:"Username updated.")}
 async function deleteAccount(){if(!window.confirm("Delete your Cookie account? This permanently removes the account and cannot be undone."))return;setNotice("For security, permanent account deletion requires Cookie account deletion service. Your account has not been deleted.")}
 async function unblock(id:string){const {error}=await supabase.rpc("unblock_user",{target:id});if(error){setNotice(error.message);return}setBlocked(x=>x.filter(p=>p.id!==id));setNotice("Account unblocked. If you were friends before the block, your friendship and existing chat are restored.")}
 function Toggle({label,k,source="settings"}:{label:string;k:string;source?:"settings"|"notifications"}){const obj=source==="settings"?settings:notifications;return <label className="cs-toggle"><span>{label}</span><input type="checkbox" checked={!!obj[k]} onChange={e=>source==="settings"?saveSettings({[k]:e.target.checked}):saveNotif(k,e.target.checked)}/></label>}
 if(!open)return null;const title=section?sections.find(s=>s.id===section)?.label:"Settings";return <div className="cs-back" onClick={()=>setOpen(false)}><aside className="cs-panel" onClick={e=>e.stopPropagation()}><header><button onClick={()=>section?setSection(null):setOpen(false)}>{section?"‹":"×"}</button><b>{title}</b></header>{notice&&<p className="cs-notice">{notice}</p>}
 {!section&&<div className="cs-list">{sections.map(s=><button key={s.id} onClick={()=>setSection(s.id)}><b>{s.label}</b><i>›</i></button>)}<button className="danger" onClick={async()=>{if(window.confirm("Log out of Cookie?")){await supabase.auth.signOut();location.reload()}}}><b>Log Out</b></button></div>}
 {section==="account"&&<div className="cs-body"><label>Email<input value={email} disabled/></label><button onClick={changePassword}>Change Password <i>›</i></button><button onClick={changeUsername}>Username <small>@{profile.username}</small><i>›</i></button><button disabled>Linked Google Account <small>{email}</small></button><button className="danger" onClick={deleteAccount}>Delete Account</button></div>}
 {section==="notifications"&&<div className="cs-body"><label className="cs-toggle cs-pause"><span><b>Pause All Notifications</b><small>Temporarily stop all Cookie notifications</small></span><input type="checkbox" checked={!notifications.enabled} onChange={e=>void saveNotif("enabled",!e.target.checked)}/></label><div className={!notifications.enabled?"cs-disabled-group":""}><Toggle label="Messages" k="messages" source="notifications"/><Toggle label="Story Replies" k="story_replies" source="notifications"/><Toggle label="Friend Requests" k="friend_requests" source="notifications"/><Toggle label="Friend Acceptances" k="friend_acceptances" source="notifications"/><Toggle label="Crumb Likes" k="crumb_likes" source="notifications"/><Toggle label="Crumb Comments" k="crumb_comments" source="notifications"/><Toggle label="Crumb Reposts" k="crumb_reposts" source="notifications"/><Toggle label="New Followers" k="new_followers" source="notifications"/></div></div>}
 {section==="appearance"&&<div className="cs-body"><label>Theme<select value={settings.theme} onChange={e=>saveSettings({theme:e.target.value})}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Accent Colour<input type="color" value={settings.accent_colour} onChange={e=>saveSettings({accent_colour:e.target.value})}/></label></div>}
 {section==="chat"&&<div className="cs-body"><label>Default disappearing messages<select value={settings.default_disappearing} onChange={e=>saveSettings({default_disappearing:e.target.value})}><option value="after_viewing">After viewing</option><option value="24_hours">24 hours</option><option value="2_days">2 days</option><option value="never">Never</option></select></label><Toggle label="Media auto-download" k="media_auto_download"/><Toggle label="Enter to send" k="enter_to_send"/><Toggle label="Notification sounds" k="notification_sounds"/><Toggle label="Typing indicators" k="typing_indicators"/><Toggle label="Online/activity status" k="activity_status"/><p className="cs-hint">Read receipts are always on in Cookie.</p></div>}
 {section==="profile"&&<div className="cs-body"><label>Display Name<input value={profile.display_name||""} onChange={e=>setProfile((p:any)=>({...p,display_name:e.target.value}))}/></label><label>Bio<textarea value={profile.bio||""} onChange={e=>setProfile((p:any)=>({...p,bio:e.target.value}))}/></label><label>Cookie Energy<input value={profile.flavour||""} onChange={e=>setProfile((p:any)=>({...p,flavour:e.target.value}))}/></label><label>Interests<input value={(profile.interests||[]).join(", ")} onChange={e=>setProfile((p:any)=>({...p,interests:e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean)}))}/></label><label>Profile Colour<input type="color" value={profile.profile_colour||"#a85f1d"} onChange={e=>setProfile((p:any)=>({...p,profile_colour:e.target.value}))}/></label><p className="cs-hint">Profile and cover photos can also be changed from your profile.</p><button className="primary" onClick={saveProfile}>Save Profile</button></div>}
 {section==="blocked"&&<div className="cs-blocked">{blocked.length?blocked.map(p=><div key={p.id}><span className="ava">{p.avatar_url?<img src={p.avatar_url} alt=""/>:<i style={{background:p.profile_colour}}>{(p.display_name||p.username)[0]}</i>}</span><span><b>{p.display_name}</b><small>@{p.username}</small></span><button onClick={()=>unblock(p.id)}>Unblock</button></div>):<p className="cs-hint">You haven't blocked anyone.</p>}</div>}
 </aside><style jsx global>{`.cs-back{position:fixed;inset:0;background:rgba(42,28,18,.22);z-index:2147483000}.cs-panel{position:absolute;right:0;top:0;width:min(430px,94vw);height:100%;overflow:auto;background:#fffaf2;color:#3b2417;padding:18px;box-shadow:-18px 0 50px #25160d2e}.cs-panel header{display:flex;gap:12px;align-items:center;padding-bottom:16px}.cs-panel header button{width:38px;height:38px;border:0;border-radius:50%;background:#f5e8d6;font-size:24px}.cs-panel header b{font-size:20px}.cs-list,.cs-body{display:grid}.cs-list>button,.cs-body>button{border:0;border-bottom:1px solid #eadbc8;background:transparent;padding:16px 8px;text-align:left;color:inherit;display:flex;justify-content:space-between;gap:8px;align-items:center}.cs-list i,.cs-body i{font-style:normal;opacity:.45}.cs-list .danger,.cs-body .danger{color:#b23b31}.cs-body>label{display:grid;gap:7px;padding:12px 2px;font-weight:700}.cs-body input,.cs-body select,.cs-body textarea{border:1px solid #e7d5bf;background:white;border-radius:12px;padding:11px;font:inherit;color:inherit}.cs-body textarea{min-height:90px;resize:vertical}.cs-toggle{grid-template-columns:1fr auto!important;align-items:center;border-bottom:1px solid #eadbc8}.cs-toggle input{width:20px;height:20px}.cs-pause{background:#fff0dc;border-radius:14px;padding:13px!important;margin-bottom:6px}.cs-pause span{display:flex;flex-direction:column;gap:3px}.cs-pause small{font-weight:500;opacity:.6}.cs-disabled-group{opacity:.45;pointer-events:none}.cs-hint{font-size:12px;opacity:.62;line-height:1.45}.cs-notice{background:#fff0d9;padding:10px;border-radius:10px;font-size:12px}.cs-body .primary{background:#5b3420;color:white;border-radius:12px;justify-content:center;margin-top:12px}.cs-blocked>div{display:grid;grid-template-columns:46px 1fr auto;gap:10px;align-items:center;padding:11px 0;border-bottom:1px solid #eadbc8}.cs-blocked span:nth-child(2){display:flex;flex-direction:column}.cs-blocked small{opacity:.55}.cs-blocked button{border:0;background:#f2dfc7;border-radius:10px;padding:8px 10px;color:inherit;font-weight:700}.ava,.ava img,.ava i{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;object-fit:cover}.ava i{color:white;font-style:normal;font-weight:900}@media(max-width:520px){.cs-panel{width:100vw;max-width:none;padding:16px;padding-bottom:max(16px,env(safe-area-inset-bottom))}}`}</style></div>
}
