"use client";
import {useEffect,useMemo,useState} from "react";

type EmojiItem={emoji:string;name:string;category:string};

const GROUPS:Record<string,string[]>={
  "😀":["😀 😃 😄 😁 😆 😅 😂 🤣 😊 😇 🙂 🙃 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🥸 🤩 🥳 🙂‍↕️ 😏 😒 🙂‍↔️ 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 😢 😭 😮‍💨 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😶‍🌫️ 😱 😨 😰 😥 😓 🤗 🤔 🫣 🤭 🫢 🫡 🤫 🫠 🤥 😶 🫥 😐 🫤 😑 😬 🙄 😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 😵‍💫 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 💀 ☠️ 👽 👾 🤖 🎃 😺 😸 😹 😻 😼 😽 🙀 😿 😾"],
  "👋":["👋 🤚 🖐️ ✋ 🖖 🫱 🫲 🫳 🫴 🫷 🫸 👌 🤌 🤏 ✌️ 🤞 🫰 🤟 🤘 🤙 👈 👉 👆 🖕 👇 ☝️ 🫵 👍 👎 ✊ 👊 🤛 🤜 👏 🙌 🫶 👐 🤲 🤝 🙏 ✍️ 💅 🤳 💪 🦾 🦿 🦵 🦶 👂 🦻 👃 🧠 🫀 🫁 🦷 🦴 👀 👁️ 👅 👄 🫦 👶 🧒 👦 👧 🧑 👱 👨 🧔 👨‍🦰 👨‍🦱 👨‍🦳 👨‍🦲 👩 👩‍🦰 👩‍🦱 👩‍🦳 👩‍🦲 🧓 👴 👵 🙍 🙎 🙅 🙆 💁 🙋 🧏 🙇 🤦 🤷 👮 👷 💂 🕵️ 👩‍⚕️ 👨‍⚕️ 👩‍🌾 👨‍🌾 👩‍🍳 👨‍🍳 👩‍🎓 👨‍🎓 👩‍🎤 👨‍🎤 👩‍🏫 👨‍🏫 👩‍🏭 👨‍🏭 👩‍💻 👨‍💻 👩‍💼 👨‍💼 👩‍🔧 👨‍🔧 👩‍🔬 👨‍🔬 👩‍🎨 👨‍🎨 👩‍🚒 👨‍🚒 👩‍✈️ 👨‍✈️ 👩‍🚀 👨‍🚀 👩‍⚖️ 👨‍⚖️ 👰 🤵 👸 🤴 🥷 🦸 🦹 🤶 🎅 🧙 🧝 🧛 🧟 🧞 🧜 🧚 👼 🤰 🫃 🫄 🤱 👩‍🍼 👨‍🍼 🧎 🧍 🚶 🏃 💃 🕺 👯 🧖 🧗 🤺 🏇 ⛷️ 🏂 🏌️ 🏄 🚣 🏊 ⛹️ 🏋️ 🚴 🚵 🤸 🤼 🤽 🤾 🤹 🧘 🛀 🛌 👭 👫 👬 💏 💑 👪 🗣️ 👤 👥 🫂"],
  "🐻":["🐵 🐒 🦍 🦧 🐶 🐕 🦮 🐕‍🦺 🐩 🐺 🦊 🦝 🐱 🐈 🐈‍⬛ 🦁 🐯 🐅 🐆 🐴 🫎 🫏 🐎 🦄 🦓 🦌 🦬 🐮 🐂 🐃 🐄 🐷 🐖 🐗 🐽 🐏 🐑 🐐 🐪 🐫 🦙 🦒 🐘 🦣 🦏 🦛 🐭 🐁 🐀 🐹 🐰 🐇 🐿️ 🦫 🦔 🦇 🐻 🐻‍❄️ 🐨 🐼 🦥 🦦 🦨 🦘 🦡 🐾 🦃 🐔 🐓 🐣 🐤 🐥 🐦 🐧 🕊️ 🦅 🦆 🦢 🦉 🦤 🪶 🦩 🦚 🦜 🪽 🐦‍⬛ 🪿 🐸 🐊 🐢 🦎 🐍 🐲 🐉 🦕 🦖 🐳 🐋 🐬 🦭 🐟 🐠 🐡 🦈 🐙 🐚 🪸 🪼 🐌 🦋 🐛 🐜 🐝 🪲 🐞 🦗 🪳 🕷️ 🕸️ 🦂 🦟 🪰 🪱 🦠 💐 🌸 💮 🪷 🏵️ 🌹 🥀 🌺 🌻 🌼 🌷 🪻 🌱 🪴 🌲 🌳 🌴 🌵 🌾 🌿 ☘️ 🍀 🍁 🍂 🍃 🍄 🪨 🪵 🌍 🌎 🌏 🌐 🗺️ 🧭 🏔️ ⛰️ 🌋 🗻 🏕️ 🏖️ 🏜️ 🏝️ 🏞️ 🌅 🌄 🌠 🎇 🎆 🌇 🌆 🏙️ 🌃 🌌 🌉 🌁"],
  "🍔":["🍏 🍎 🍐 🍊 🍋 🍋‍🟩 🍌 🍉 🍇 🍓 🫐 🍈 🍒 🍑 🥭 🍍 🥥 🥝 🍅 🍆 🥑 🫛 🥦 🥬 🥒 🌶️ 🫑 🌽 🥕 🫒 🧄 🧅 🥔 🍠 🫘 🌰 🫚 🫜 🥐 🥯 🍞 🥖 🫓 🥨 🥞 🧇 🧀 🍖 🍗 🥩 🥓 🍔 🍟 🍕 🌭 🥪 🌮 🌯 🫔 🥙 🧆 🥚 🍳 🥘 🍲 🫕 🥣 🥗 🍿 🧈 🧂 🥫 🍱 🍘 🍙 🍚 🍛 🍜 🍝 🍠 🍢 🍣 🍤 🍥 🥮 🍡 🥟 🥠 🥡 🦀 🦞 🦐 🦑 🦪 🍦 🍧 🍨 🍩 🍪 🎂 🍰 🧁 🥧 🍫 🍬 🍭 🍮 🍯 🍼 🥛 ☕ 🫖 🍵 🍶 🍾 🍷 🍸 🍹 🍺 🍻 🥂 🥃 🫗 🥤 🧋 🧃 🧉 🧊 🥢 🍽️ 🍴 🥄 🔪 🫙 🏺"],
  "⚽":["⚽ 🏀 🏈 ⚾ 🥎 🎾 🏐 🏉 🥏 🎱 🪀 🏓 🏸 🏒 🏑 🥍 🏏 🪃 🥅 ⛳ 🪁 🏹 🎣 🤿 🥊 🥋 🎽 🛹 🛼 🛷 ⛸️ 🥌 🎿 ⛷️ 🏂 🪂 🏋️ 🤼 🤸 ⛹️ 🤺 🤾 🏌️ 🏇 🧘 🏄 🏊 🤽 🚣 🧗 🚵 🚴 🏆 🥇 🥈 🥉 🏅 🎖️ 🏵️ 🎗️ 🎫 🎟️ 🎪 🤹 🎭 🩰 🎨 🎬 🎤 🎧 🎼 🎹 🥁 🪘 🪇 🎷 🎺 🪗 🎸 🪕 🎻 🪈 🎲 ♟️ 🎯 🎳 🎮 🎰 🧩"],
  "🚗":["🚗 🚕 🚙 🚌 🚎 🏎️ 🚓 🚑 🚒 🚐 🛻 🚚 🚛 🚜 🏍️ 🛵 🦽 🦼 🛺 🚲 🛴 🛹 🛼 🚨 🚔 🚍 🚘 🚖 🛞 🚡 🚠 🚟 🚃 🚋 🚞 🚝 🚄 🚅 🚈 🚂 🚆 🚇 🚊 🚉 ✈️ 🛫 🛬 🛩️ 💺 🛰️ 🚀 🛸 🚁 🛶 ⛵ 🚤 🛥️ 🛳️ ⛴️ 🚢 ⚓ 🛟 ⛽ 🚧 🚦 🚥 🗺️ 🗿 🗽 🗼 🏰 🏯 🏟️ 🎡 🎢 🎠 ⛲ ⛱️ 🏖️ 🏝️ 🏜️ 🌋 ⛰️ 🏔️ 🏕️ ⛺ 🛖 🏠 🏡 🏘️ 🏚️ 🏗️ 🏭 🏢 🏬 🏣 🏤 🏥 🏦 🏨 🏪 🏫 🏩 💒 🏛️ ⛪ 🕌 🕍 🛕 🕋 ⛩️ 🛤️ 🛣️ 🗾 🎑 🏞️ 🌅 🌄 🌠 🎇 🎆 🌇 🌆 🏙️ 🌃 🌌 🌉 🌁"],
  "💡":["⌚ 📱 📲 💻 ⌨️ 🖥️ 🖨️ 🖱️ 🖲️ 🕹️ 🗜️ 💽 💾 💿 📀 📼 📷 📸 📹 🎥 📽️ 🎞️ 📞 ☎️ 📟 📠 📺 📻 🎙️ 🎚️ 🎛️ 🧭 ⏱️ ⏲️ ⏰ 🕰️ ⌛ ⏳ 📡 🔋 🪫 🔌 💡 🔦 🕯️ 🪔 🧯 🛢️ 💸 💵 💴 💶 💷 🪙 💰 💳 💎 ⚖️ 🪜 🧰 🪛 🔧 🔨 ⚒️ 🛠️ ⛏️ 🪏 🔩 ⚙️ 🧱 ⛓️ ⛓️‍💥 🧲 🔫 💣 🧨 🪓 🔪 🗡️ ⚔️ 🛡️ 🚬 ⚰️ 🪦 ⚱️ 🏺 🔮 📿 🧿 🪬 💈 ⚗️ 🔭 🔬 🕳️ 🩹 🩺 🩻 🩼 💊 💉 🩸 🧬 🦠 🧫 🧪 🌡️ 🧹 🪠 🧺 🧻 🚽 🚿 🛁 🪥 🪒 🧼 🫧 🪥 🧽 🧴 🛎️ 🔑 🗝️ 🚪 🪑 🛋️ 🛏️ 🛌 🧸 🪆 🖼️ 🪞 🪟 🛍️ 🛒 🎁 🎈 🎏 🎀 🪄 🪅 🎊 🎉 🪩 🧧 ✉️ 📩 📨 📧 💌 📥 📤 📦 🏷️ 🪧 📪 📫 📬 📭 📮 📯 📜 📃 📄 📑 🧾 📊 📈 📉 🗒️ 🗓️ 📆 📅 🗑️ 📇 🗃️ 🗳️ 🗄️ 📋 📁 📂 🗂️ 🗞️ 📰 📓 📔 📒 📕 📗 📘 📙 📚 📖 🔖 🧷 🔗 📎 🖇️ 📐 📏 🧮 📌 📍 ✂️ 🖊️ 🖋️ ✒️ 🖌️ 🖍️ 📝 ✏️ 🔍 🔎 🔏 🔐 🔒 🔓"],
  "❤️":["❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 🩷 🩵 🩶 💔 ❤️‍🔥 ❤️‍🩹 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟 ☮️ ✝️ ☪️ 🕉️ ☸️ ✡️ 🔯 🕎 ☯️ ☦️ 🛐 ⛎ ♈ ♉ ♊ ♋ ♌ ♍ ♎ ♏ ♐ ♑ ♒ ♓ 🆔 ⚛️ 🉑 ☢️ ☣️ 📴 📳 🈶 🈚 🈸 🈺 🈷️ ✴️ 🆚 💮 🉐 ㊙️ ㊗️ 🈴 🈵 🈹 🈲 🅰️ 🅱️ 🆎 🆑 🅾️ 🆘 ❌ ⭕ 🛑 ⛔ 📛 🚫 💯 💢 ♨️ 🚷 🚯 🚳 🚱 🔞 📵 🚭 ❗ ❕ ❓ ❔ ‼️ ⁉️ 🔅 🔆 〽️ ⚠️ 🚸 🔱 ⚜️ 🔰 ♻️ ✅ 🈯 💹 ❇️ ✳️ ❎ 🌐 💠 Ⓜ️ 🌀 💤 🏧 🚾 ♿ 🅿️ 🛗 🈳 🈂️ 🛂 🛃 🛄 🛅 🚹 🚺 🚼 ⚧️ 🚻 🚮 🎦 📶 🈁 🔣 ℹ️ 🔤 🔡 🔠 🆖 🆗 🆙 🆒 🆕 🆓 0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟 🔢 #️⃣ *️⃣ ⏏️ ▶️ ⏸️ ⏯️ ⏹️ ⏺️ ⏭️ ⏮️ ⏩ ⏪ ⏫ ⏬ ◀️ 🔼 🔽 ➡️ ⬅️ ⬆️ ⬇️ ↗️ ↘️ ↙️ ↖️ ↕️ ↔️ ↪️ ↩️ ⤴️ ⤵️ 🔀 🔁 🔂 🔄 🔃 🎵 🎶 ➕ ➖ ➗ ✖️ 🟰 ♾️ 💲 💱 ™️ ©️ ®️ 〰️ ➰ ➿ 🔚 🔙 🔛 🔝 🔜 ✔️ ☑️ 🔘 🔴 🟠 🟡 🟢 🔵 🟣 ⚫ ⚪ 🟤 🔺 🔻 🔸 🔹 🔶 🔷 🔳 🔲 ▪️ ▫️ ◾ ◽ ◼️ ◻️ 🟥 🟧 🟨 🟩 🟦 🟪 ⬛ ⬜ 🟫 🔈 🔇 🔉 🔊 🔔 🔕 📣 📢 👁️‍🗨️ 💬 💭 🗯️ ♠️ ♣️ ♥️ ♦️ 🃏 🎴 🀄 🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛 🕜 🕝 🕞 🕟 🕠 🕡 🕢 🕣 🕤 🕥 🕦 🕧"],
  "🏳️":["🏁 🚩 🎌 🏴 🏳️ 🏳️‍🌈 🏳️‍⚧️ 🏴‍☠️ 🇬🇭 🇺🇸 🇬🇧 🇨🇦 🇦🇺 🇳🇬 🇿🇦 🇰🇪 🇪🇹 🇪🇬 🇲🇦 🇩🇪 🇫🇷 🇮🇹 🇪🇸 🇵🇹 🇳🇱 🇧🇪 🇨🇭 🇸🇪 🇳🇴 🇩🇰 🇫🇮 🇮🇪 🇵🇱 🇺🇦 🇷🇺 🇹🇷 🇸🇦 🇦🇪 🇶🇦 🇮🇱 🇮🇳 🇵🇰 🇧🇩 🇱🇰 🇨🇳 🇯🇵 🇰🇷 🇸🇬 🇲🇾 🇮🇩 🇵🇭 🇹🇭 🇻🇳 🇳🇿 🇧🇷 🇦🇷 🇲🇽 🇨🇱 🇨🇴 🇵🇪 🇯🇲 🇨🇺 🇹🇹 🇧🇸 🇧🇧 🇬🇩 🇱🇷 🇸🇱 🇨🇮 🇸🇳 🇹🇬 🇧🇯 🇧🇫 🇲🇱 🇳🇪 🇬🇲 🇬🇼 🇨🇲 🇬🇦 🇨🇬 🇨🇩 🇺🇬 🇹🇿 🇷🇼 🇧🇮 🇿🇲 🇿🇼 🇧🇼 🇳🇦 🇲🇿 🇦🇴 🇲🇬 🇲🇺 🇸🇨 🇱🇸 🇸🇿 🇸🇸 🇸🇩 🇸🇴 🇩🇿 🇹🇳 🇱🇾 🇲🇷 🇨🇻 🇨🇫 🇹🇩 🇬🇶 🇪🇷 🇩🇯 🇰🇲 🇲🇼 🇸🇹 🇺🇳 🇪🇺"]
};

const NAMES:Record<string,string>={
 "😂":"face with tears of joy laugh funny","🤣":"rolling on floor laughing rofl","😭":"loudly crying sad tears","🥹":"holding back tears touched","😍":"heart eyes love","🥰":"smiling hearts love","😘":"kiss","😎":"sunglasses cool","🥳":"party celebration birthday","🤔":"thinking","🤭":"giggle shy","🤯":"mind blown shocked","💀":"skull dead lol","🔥":"fire hot lit","✨":"sparkles shine","💯":"hundred perfect","🙏":"pray prayer please thanks faith","🙏🏾":"pray prayer please thanks faith","🙌":"raised hands praise celebrate","🙌🏾":"raised hands praise celebrate","👏":"clap applause","👏🏾":"clap applause","👀":"eyes look watch","❤️":"red heart love","💕":"two hearts love","💔":"broken heart","❤️‍🔥":"heart on fire love passion","✝️":"cross christian church faith Jesus","⛪":"church christian faith","🕊️":"dove peace holy spirit","🍪":"cookie biscuit","🎉":"party popper celebration","🎂":"birthday cake","🎶":"music notes song","🎤":"microphone sing","⚽":"football soccer","🏀":"basketball","🎮":"game gaming controller","📱":"phone mobile","💻":"laptop computer","💡":"light bulb idea","🔔":"bell notification","📍":"location pin","📅":"calendar date","⏰":"alarm clock time","🚗":"car vehicle","✈️":"airplane travel flight","🏠":"house home","🌍":"earth world africa globe","☀️":"sun sunny","🌙":"moon night","🌸":"flower blossom","🌹":"rose flower love","🇬🇭":"Ghana flag gh","🇺🇸":"United States USA America flag","🇬🇧":"United Kingdom UK Britain flag","🇳🇬":"Nigeria flag","🇿🇦":"South Africa flag","🇰🇪":"Kenya flag","🇨🇦":"Canada flag","🇦🇺":"Australia flag","🇫🇷":"France flag","🇩🇪":"Germany flag","🇮🇹":"Italy flag","🇪🇸":"Spain flag","🇧🇷":"Brazil flag","🇯🇵":"Japan flag","🇨🇳":"China flag","🇮🇳":"India flag","🇺🇳":"United Nations UN flag"
};

const CATEGORY_NAMES:Record<string,string>={"😀":"Smileys","👋":"People","🐻":"Animals & Nature","🍔":"Food & Drink","⚽":"Activities","🚗":"Travel & Places","💡":"Objects","❤️":"Symbols","🏳️":"Flags"};

function buildData():EmojiItem[]{const out:EmojiItem[]=[];const seen=new Set<string>();Object.entries(GROUPS).forEach(([cat,rows])=>rows.join(" ").split(/\s+/).filter(Boolean).forEach(emoji=>{if(seen.has(emoji))return;seen.add(emoji);out.push({emoji,name:NAMES[emoji]||"",category:cat})}));return out}
const ALL=buildData();

function insertEmoji(emoji:string){
 const ta=document.querySelector(".csc-canvas textarea") as HTMLTextAreaElement|null;if(!ta)return;
 const proto=window.HTMLTextAreaElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,"value")?.set;if(!setter)return;
 const start=ta.selectionStart??ta.value.length,end=ta.selectionEnd??start,next=ta.value.slice(0,start)+emoji+ta.value.slice(end);
 setter.call(ta,next);ta.dispatchEvent(new Event("input",{bubbles:true}));requestAnimationFrame(()=>{ta.focus();const p=start+emoji.length;ta.setSelectionRange(p,p)});
}

export default function CookieFullEmojiPicker(){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(""),[category,setCategory]=useState("😀"),[recent,setRecent]=useState<string[]>([]);
 useEffect(()=>{try{setRecent(JSON.parse(localStorage.getItem("cookie-recent-emojis")||"[]"))}catch{}
   const onClick=(e:MouseEvent)=>{const btn=(e.target as HTMLElement).closest('button[aria-label="Open emoji tray"]');if(!btn)return;e.preventDefault();e.stopImmediatePropagation();setOpen(v=>!v)};
   document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true);
 },[]);
 useEffect(()=>{const style=document.createElement("style");style.dataset.cookieFullEmoji="1";style.textContent=".csc-emoji-tray{display:none!important}";document.head.appendChild(style);return()=>style.remove()},[]);
 const items=useMemo(()=>{const q=query.trim().toLowerCase();if(q)return ALL.filter(x=>(x.name+" "+CATEGORY_NAMES[x.category]+" "+x.emoji).toLowerCase().includes(q));if(category==="🕘")return recent.map(e=>ALL.find(x=>x.emoji===e)).filter(Boolean) as EmojiItem[];return ALL.filter(x=>x.category===category)},[query,category,recent]);
 function choose(e:string){insertEmoji(e);const next=[e,...recent.filter(x=>x!==e)].slice(0,36);setRecent(next);try{localStorage.setItem("cookie-recent-emojis",JSON.stringify(next))}catch{}}
 if(!open)return null;
 return <div className="cfep" onClick={e=>e.stopPropagation()}>
   <div className="cfep-search"><span>⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search emojis…"/><button onClick={()=>setOpen(false)}>×</button></div>
   {!query&&<div className="cfep-tabs"><button className={category==="🕘"?"active":""} onClick={()=>setCategory("🕘")} title="Recently used">🕘</button>{Object.keys(GROUPS).map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)} title={CATEGORY_NAMES[c]}>{c}</button>)}</div>}
   <div className="cfep-label">{query?`${items.length} results`:category==="🕘"?"Recently Used":CATEGORY_NAMES[category]}</div>
   <div className="cfep-grid">{items.length?items.map((x,i)=><button key={`${x.emoji}-${i}`} onClick={()=>choose(x.emoji)} title={x.name||CATEGORY_NAMES[x.category]}>{x.emoji}</button>):<p>No emojis found</p>}</div>
   <style jsx global>{`.cfep{position:fixed;z-index:2147483600;left:50%;bottom:92px;transform:translateX(-50%);width:min(520px,calc(100vw - 28px));height:min(460px,58vh);display:flex;flex-direction:column;background:#fffaf4;color:#382317;border:1px solid #eadfce;border-radius:22px;box-shadow:0 22px 70px rgba(0,0,0,.3);overflow:hidden}.cfep-search{display:flex;align-items:center;gap:8px;padding:12px;border-bottom:1px solid #eee2d4}.cfep-search>span{opacity:.55;font-size:20px}.cfep-search input{flex:1;border:0;outline:0;background:#f5ede3;border-radius:13px;padding:11px 12px;font:600 14px system-ui;color:#382317}.cfep-search button{border:0;background:transparent;font-size:24px;color:#6b5547}.cfep-tabs{display:flex;gap:3px;overflow-x:auto;padding:8px 10px;border-bottom:1px solid #eee2d4;scrollbar-width:none}.cfep-tabs::-webkit-scrollbar{display:none}.cfep-tabs button{flex:0 0 38px;width:38px;height:38px;border:0;border-radius:11px;background:transparent;font-size:21px}.cfep-tabs button.active{background:#eee0cf}.cfep-label{padding:8px 14px 3px;font:800 11px system-ui;letter-spacing:.04em;text-transform:uppercase;color:#8a7465}.cfep-grid{flex:1;display:grid;grid-template-columns:repeat(8,1fr);gap:2px;align-content:start;overflow-y:auto;padding:8px 10px 14px}.cfep-grid button{border:0;background:transparent;border-radius:10px;aspect-ratio:1;font-size:27px;cursor:pointer}.cfep-grid button:hover{background:#f2e7d9}.cfep-grid p{grid-column:1/-1;text-align:center;padding:40px 10px;color:#8a7465}@media(max-width:600px){.cfep{bottom:0;width:100%;height:55vh;border-radius:22px 22px 0 0}.cfep-grid{grid-template-columns:repeat(7,1fr)}.cfep-grid button{font-size:25px}}`}</style>
 </div>
}
